CLUSTERS="esy-digital,esy2-digital,izm-digital"
NAMESPACE_ENABLED="true"
POD_HEALTH_ENABLED="true"
ZABBIX_ENABLED="true"
MAIL_ENABLED="true"
SEVERITY="5"
NODE="ZEUS"
DEPARTMENT="ZEUS"
POD_HEALTH_ALERTKEY="OCP_POD_HEALTH"
ALERTGROUP="DXL"
MAIL_TO="canberk.gurcan@vodafone.com"
MAIL_CC="digitalservicesreliability.tr@vodafone.com,sot.zeus.devops.team.tr@vodafone.com"
